# A list of tracer variable code names.
# Depending on your model runs these may change.
# Worst case, you can hard code the variable names in the routines...

temp.code   <- "temp"
u.code      <- "u"
h2o.code    <- "q"
trop.hgt.code  <- "ht_1"
o3.code     <- "tracer1"
no.code     <- "tracer2"
noy.code    <- "tracer4"
n2o5.code   <- "tracer5"
ho2no2.code <- "tracer6"
hono2.code  <- "tracer7"
h2o2.code   <- "tracer8"
ch4.code    <- "tracer9"
co.code     <- "tracer10"
hcho.code   <- "tracer11"
pan.code    <- "tracer17"
clo.code    <- "field542"
n2o.code    <- "field549"
clono2.code <- "field554"
oh.code     <- "field581"
ho2.code    <- "field582"
age.air     <- "SST" 
no2.code    <- "tracer4"
bro.code    <- "field1861_1"
hcl.code    <- "field1861_2"
cly.code    <- "field1861_3"
ho2no.code  <- "field581_1"
meo2no.code <- "field582"
ro2no.code  <- "field583"
ohrcooh.code<- "field584"
ohrono2.code<- "field585"
hvrono2.code<- "field586"
ohpan.code  <- "field587"
o1dh2o.code <- "field591"
mlr.code    <- "field592"
ho2o3.code  <- "field593"
oho3.code   <- "field594"
o3alk.code  <- "field595"
n2o5h2o.code<- "field596"
no3loss.code<- "field597"
o3.dd.code  <- "temp_1"
noy.dd.code <- "salinity"
noy.wd.code <- "field611"
oh.no2.code <- "HTN"
oh.ch4.rxn.code <- "field621" #"snowfall"
air.mass    <- "field643"
